List images = [
  'assets/images/assassain.jfif',
  'assets/images/bugatti.jfif',
  'assets/images/cat.jfif',
  'assets/images/code.jpg',
  'assets/images/codep.jpg',
  'assets/images/dodge viper.jfif',
  'assets/images/flower.jpg',
  'assets/images/flowerw.jpg',
  'assets/images/aston martin.jfif',
  'assets/images/ford shelby.jfif',
  'assets/images/lamborgini.jfif',
  'assets/images/image.jpg',
  'assets/images/image2.jpg',
  'assets/images/lake.jpg',
  'assets/images/moon.jpg',
  'assets/images/moonf.jpg',
  'assets/images/nature.jpg',
  'assets/images/stray.png',
  'assets/images/OIP.jfif',
  'assets/images/pink flower.jfif',
  'assets/images/stray cat.jfif',
  'assets/images/syndicate.jfif',
  'assets/images/tomb.jfif',
  'assets/images/tomb 2.jfif',
  'assets/images/tombb.jfif',
  'assets/images/unity.jfif',
  'assets/images/wp.jpg',
  'assets/images/yasmine.jfif',
];
List albums = [
  {'title': 'Anime', 'image': 'assets/images/wp.jpg'},
  {'title': 'Flowers', 'image': 'assets/images/flower.jpg'},
  {'title': 'Cars', 'image': 'assets/images/bugatti.jfif'},
  {'title': 'Games', 'image': 'assets/images/syndicate.jfif'},
  {'title': 'nature', 'image': 'assets/images/lake.jpg'},
];
